### ISSUE TITLE
Originaltext nicht mehr erreichbar

### ISSUE THREAD

**Issue by mwardermann** [dotnet/dotnet-api-docs.de-de#11]
In der Dokumentation konnte ich keine Möglichkeit mehr finden,  zum englischen Originaltext zu gelangen.
Die deutsche Übersetzung ist meistens nicht adäquat.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 50675e29-d746-a726-838c-7db75d089995
* Version Independent ID: bfdbf4fc-f2df-f2dc-b4ab-f46d8008830c
* Content: [Thread.CurrentCulture Property (System.Threading)](https://docs.microsoft.com/de-de/dotnet/api/system.threading.thread.currentculture?view=netframework-4.7.2)
* Content Source: [xml/System.Threading/Thread.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Threading/Thread.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #1460](https://github.com/dotnet/dotnet-api-docs/issues/1460) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @mwardermann 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/dotnet/dotnet-api-docs/issues/1460. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Die Seite von en-us ist hier:  https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.currentculture?view=netframework-4.7.2

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @mwardermann

Vielen Dank für Ihr Feedback. Die betroffene Seite wurde maschinenübersetzt. Daher kann es sein, dass der Inhalt nicht immer verständlich ist. Wir haben vor Kurzem die Option „Read in English“ (Auf Englisch lesen) rechts hinzugefügt, sodass Sie zur englischen Version wechseln können, ohne die Spracheinstellungen ändern zu müssen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
