### ISSUE TITLE
Plan to support System.DirectorySercives to UWP

### ISSUE THREAD

**Issue by mani009** [dotnet/dotnet-api-docs.de-de#13]
Is there a plan to support DirectoryServices to UWP? Or is it another wo to validate windows offline cached credentails with PrincipalContext ContextType.Machine?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fd43c5b1-2ae5-247d-6831-0ff500b07096
* Version Independent ID: c7aa119f-d0e4-ab57-7b4e-91b1369ecfbe
* Content: [System.DirectoryServices Namespace](https://docs.microsoft.com/de-de/dotnet/api/system.directoryservices?view=netframework-4.7.2)
* Content Source: [xml/ns-System.DirectoryServices.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/ns-System.DirectoryServices.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @mani009 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
