### ISSUE TITLE
Memory class and PInvoke

### ISSUE THREAD

**Issue by dotChris90** [dotnet/dotnet-api-docs.de-de#15]
I just would like to know if memory class can interact via pinvoke with unmanaged libraries?

Span is extrem nice because it offers us developers the possibility e.g. to take a C function in DLL with signature "void func(void* ptr, int length)" and map this to C# "void func(ref float ptr, int length)" and pass a span via MemoryMarshal.GetReference. 

Before we always had to take IntPtr which was not always the best option. 

What about  memory? Does it also offers such PInvoke mechansism? So we could store the memory class as field of a class and use this field to interact with void* based C functions?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b660e115-b744-c369-b67c-26a7e4259300
* Version Independent ID: f0acf3f5-918a-be84-e756-e70e3399465f
* Content: [Memory&lt;T&gt; Struct (System)](https://docs.microsoft.com/de-de/dotnet/api/system.memory-1?view=netcore-2.2)
* Content Source: [xml/System/Memory`1.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System/Memory`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @dotChris90 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback/Feedback zu Produkten" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
