### ISSUE TITLE
Dispose trigger SynchronizationLockException

### ISSUE THREAD

**Issue by trivalik** [dotnet/dotnet-api-docs.de-de#16]
Dispose could generate, I am not sure If debugger was triggering this issue:
System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.TimerQueueTimer.Close()
   at System.Threading.Timer.Dispose()

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e5c971a8-7364-56d8-5c40-215987277c41
* Version Independent ID: 78e57b9c-0f9d-ed5a-0b6e-148597326315
* Content: [Timer.Dispose Method (System.Threading)](https://docs.microsoft.com/de-de/dotnet/api/system.threading.timer.dispose?view=netframework-4.7.2)
* Content Source: [xml/System.Threading/Timer.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Threading/Timer.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
