### ISSUE TITLE
Übersetzung Hinweise

### ISSUE THREAD

**Issue by ngzero** [dotnet/dotnet-api-docs.de-de#20]
Der Abschnitt "Hinweise" ist sehr schlecht ins deutsche übersetzt und ergibt keinen Sinn.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 18e5d41c-df95-6b00-34ae-9b6771d2013c
* Version Independent ID: 3e45cd7b-7d60-3b64-152b-70ff4af85c61
* Content: [SerializationInfo.GetValue(String, Type) Method (System.Runtime.Serialization)](https://docs.microsoft.com/de-de/dotnet/api/system.runtime.serialization.serializationinfo.getvalue?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.Serialization/SerializationInfo.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Runtime.Serialization/SerializationInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hallo, @ngzero 

Vielen Dank für Ihr Feedback. Die betroffene Seite wurde maschinenübersetzt. Daher kann es sein, dass der Inhalt nicht immer verständlich ist. Wir haben vor Kurzem die Option „Read in English“ (Auf Englisch lesen) rechts hinzugefügt, sodass Sie zur englischen Version wechseln können, ohne die Spracheinstellungen ändern zu müssen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
