### ISSUE TITLE
VB-Hilfe-Seite mit C# Beispiel-Code

### ISSUE THREAD

**Issue by DBEKrause** [dotnet/dotnet-api-docs.de-de#22]
[Hier Feedback eingeben]
Die reinen Erklärungen auf der Seite sind sicherlich hilfreich.
Nun habe ich die F1-Taste aus einer Visual-Basic-Applikation heraus gedrückt, die Beispiel-Codes sind jedoch in C# geschrieben, das ist definitiv nicht hilfreich, nicht einmal dann, wenn man erweiterte Grundkenntnisse darin hat; ich erwarte an dieser Stelle einen VB-Beispiel-Code, alles andere ist kontra-produktiv.
MfG Erwin Krause 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b506a9fe-8a9e-4ea4-705e-95896479d155
* Version Independent ID: 12a50eb1-1012-49b3-fad8-5c965e4534ce
* Content: [WebBrowser.Navigated Event (System.Windows.Forms)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.webbrowser.navigated?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(System.Windows.Forms.WebBrowser.Navigated);k(System.Windows.Forms.WebBrowser);k(VS.Properties);k(System.Windows.Forms.WebBrowser);k(Designer_System.Windows.Forms.Design.FormDocumentDesigner);k(VisualSelection);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/WebBrowser.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Forms/WebBrowser.xml)
* Product: **dotnet-api**
* Technology: **system.windows**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2244](https://github.com/dotnet/dotnet-api-docs/issues/2244) via [**ZenHub**](https://www.zenhub.com/)
