### ISSUE TITLE
Antwort VB help page with C # example code (#2244)

### ISSUE THREAD

**Issue by DBEKrause** [dotnet/dotnet-api-docs.de-de#23]
Sehr geehrte Damen und Herren,

da muss ich wohl um Verzeihung bitten.
In meiner Ungeduld hatte ich nicht auf die zum Dokument gehörende Menüleiste geachtet, in deren rechten Bereich die Sprache des Beispiel-Codes ausgewählt werden kann.
Das habe ich getan, und jetzt kann ich wirklich sagen, dass diese Hilfeseite gut gemacht ist und mir bei der Lösung meiner Herausforderung sehr nützlich sein wird.

MfG
Erwin Krause
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b506a9fe-8a9e-4ea4-705e-95896479d155
* Version Independent ID: 12a50eb1-1012-49b3-fad8-5c965e4534ce
* Content: [WebBrowser.Navigated Event (System.Windows.Forms)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.webbrowser.navigated?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(System.Windows.Forms.WebBrowser.Navigated);k(System.Windows.Forms.WebBrowser);k(VS.Properties);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/WebBrowser.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Forms/WebBrowser.xml)
* Product: **dotnet-api**
* Technology: **system.windows**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hallo, @DBEKrause 

vielen Dank für Ihr Feedback. Es freut uns, dass Sie mir unserer Dokumentation zufrieden sind. 
Sie können gerne weiterhin Feedback abgeben, damit wir die Servicequalität kontinuierlich verbessern können. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
