### ISSUE TITLE
Does not work at all!

### ISSUE THREAD

**Issue by dreamy-s** [dotnet/dotnet-api-docs.de-de#26]
Hello, This example does not work. You will always get a ValidationException while reading thorugh the xsd Example. 
And if you use own things and even let visual studio create your xsd, everythin is going to be valide. There are no exceptions thrown. The only Ecxeptions that you can get is from the XmlReader when you add a opening tag but do not close it. Thats it! It doesn't matter what you are doing, this page and function is useless. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0f2f25ce-a5fc-e17e-6418-38a35784f990
* Version Independent ID: 19a31cc9-1d20-1aa0-7792-e56385d5f5fe
* Content: [XmlSchemaSet Class (System.Xml.Schema)](https://docs.microsoft.com/de-de/dotnet/api/system.xml.schema.xmlschemaset?view=netframework-4.8#feedback)
* Content Source: [xml/System.Xml.Schema/XmlSchemaSet.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Xml.Schema/XmlSchemaSet.xml)
* Product: **dotnet-api**
* Technology: **system.xml**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2497](https://github.com/dotnet/dotnet-api-docs/issues/2497) via [**ZenHub**](https://www.zenhub.com/)
