### ISSUE TITLE
Typo in German language

### ISSUE THREAD

**Issue by h0ch5tr4355** [dotnet/dotnet-api-docs.de-de#29]
"Das folgende Beispiel erstellt die Umgebungsvariablen für die EnvironmentVariableTarget.Process, EnvironmentVariableTarget.User, und Machine ausgerichtet ist, überprüft, ob die Registrierung des Betriebssystems, die Benutzer und Computer-Umgebungsvariablen enthält, und löscht dann die Umgebung Variablen."

At the end "Umgebung Variablen" is misleading (resp. wrong), should be corrected to "Umgebungsvariablen".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e06179fc-764c-c3d4-d3f2-06c67dc5e33c
* Version Independent ID: 6e7f0f0d-2e0d-fd60-0f5d-7a2c7ee82f87
* Content: [Environment.SetEnvironmentVariable Method (System)](https://docs.microsoft.com/de-de/dotnet/api/system.environment.setenvironmentvariable?view=netframework-4.8#feedback)
* Content Source: [xml/System/Environment.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System/Environment.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @h0ch5tr4355
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @h0ch5tr4355
Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/dotnet/api/system.environment.setenvironmentvariable?view=netframework-4.8#feedback 
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
