### ISSUE TITLE
Danke schön :)

### ISSUE THREAD

**Issue by Siox0911** [dotnet/dotnet-api-docs.de-de#3]
Ich habe mich die letzte Zeit immer gefragt wie man wohl Verschlüsselung in C# theoretisch umsetzen könnte. Der BigInteger bringt auf den ersten Blick eine reichhaltige Funktionalität dafür mit. Ich bin wirklich begeistert. Danke... :)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 33f9cc30-f90e-fdc4-5b9e-00c5018e8348
* Version Independent ID: 28db996d-f438-e97d-ea1e-bccdeab8d7dd
* Content: [BigInteger Struct (System.Numerics)](https://docs.microsoft.com/de-de/dotnet/api/system.numerics.biginteger?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Numerics/BigInteger.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Numerics/BigInteger.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hallo, @Siox0911, 

vielen Dank für Ihr Feedback. Es freut uns, dass Sie mir unserer Dokumentation zufrieden sind. 
Sie können gerne weiterhin Feedback abgeben, damit wir die Servicequalität kontinuierlich verbessern können. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
