### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by soelax** [dotnet/dotnet-api-docs.de-de#37]
The German translation only shows German headings, but the content is not translated.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b078b60f-a8ae-9858-17b9-499301b5bf24
* Version Independent ID: 99b1e1a1-7e08-2548-07ac-06bb9dc43fe6
* Content: [Button.IsDefault Property (System.Windows.Controls)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.controls.button.isdefault?view=netframework-4.8#feedback)
* Content Source: [xml/System.Windows.Controls/Button.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Controls/Button.xml)
* Product: **dotnet-api**
* Technology: **system.windows**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @soelax
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @soelax 
I cannot repro this error, can you please check if the "Auf Englisch lesen" slider is active?
![imagen](https://user-images.githubusercontent.com/26746247/62213132-a2c86400-b378-11e9-8bf9-075b6b9b9e31.png)

**Comment by soelax** [comment]
Hi @CeciAc,
now it appears perfectly translated - headings **and** text.
Strange, but good.
Sorry for disturbing then. ;)
