### ISSUE TITLE
HttpClient GetAsync(string) Wrong description of Exception

### ISSUE THREAD

**Issue by Nplu5** [dotnet/dotnet-api-docs.de-de#39]
The Documentation states two Exceptions for the `HttpClient.GetAsync(string)` method: namely _HttpRequestException_ when Http related issues occur and _ArgumentException_ when problems with the passed Uri (as a string) occur. When trying this out and passing a string containing null the Exception raised was a _InvalidOperationException_ instead of the expected _ArgumentException_. Here is a gist with the code to test from a dotnet console application: https://gist.github.com/Nplu5/f4703cbd6eb8ee33b36cc4b0157b05cb 

If you need any further information I am happy to provide them.
![ExampleOutput](https://user-images.githubusercontent.com/22539404/63115040-9eb25e00-bf96-11e9-82c2-a4d166811348.PNG)
 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a1ad48e9-93a3-81f4-6270-a8f033c8570f
* Version Independent ID: 4674b02c-b277-63c7-d87d-54ae950bcaae
* Content: [HttpClient.GetAsync Method (System.Net.Http)](https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httpclient.getasync?view=netcore-2.2)
* Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Net.Http/HttpClient.xml)
* Product: **dotnet-api**
* Technology: **system.net**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by srvbpigh** [comment]
Hello, @Nplu5
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Nplu5

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by Nplu5** [comment]
Sorry for not being specific in this point but the documentation is differing from the actual behavior. That means it should be stated that a _InvalidOperationException_ will be thrown instead of the mentioned _ArgumentExceptiion_, as it is the behavior when passing the mentioned null string to the GetAsync Method.
