### ISSUE TITLE
Why no using on ICryptoTransform decryptor

### ISSUE THREAD

**Issue by muhmuhhum** [dotnet/dotnet-api-docs.de-de#41]
why is there no using for  ICryptoTransform decryptor = rijAlg.CreateDecryptor(rijAlg.Key, rijAlg.IV);
It also implements IDisposable?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a31cf3bd-db3b-3b0b-bdc7-26d078533928
* Version Independent ID: 08b75289-960d-22dd-b268-717d279af8a9
* Content: [RijndaelManaged Class (System.Security.Cryptography)](https://docs.microsoft.com/de-de/dotnet/api/system.security.cryptography.rijndaelmanaged?view=netframework-4.8)
* Content Source: [xml/System.Security.Cryptography/RijndaelManaged.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Security.Cryptography/RijndaelManaged.xml)
* Product: **dotnet-api**
* Technology: **system.security**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @muhmuhhum
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @muhmuhhum

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
