### ISSUE TITLE
Deutsch - Remarks

### ISSUE THREAD

**Issue by Siox0911** [dotnet/dotnet-api-docs.de-de#5]
Hallo zusammen,
ich kann den Abschnitt Remarks auf Deutsch nicht verstehen. Und selbst auf English vermisse ich im Beispiel das [?] Fragezeichen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9776ac25-b22e-20c8-4c75-dd4a988da2b3
* Version Independent ID: 549bf386-3f12-53a9-a29c-f7475e063cd5
* Content: [SqlCommand.Parameters Property (System.Data.SqlClient)](https://docs.microsoft.com/de-de/dotnet/api/system.data.sqlclient.sqlcommand.parameters?view=netframework-4.7.2#System_Data_SqlClient_SqlCommand_Parameters)
* Content Source: [xml/System.Data.SqlClient/SqlCommand.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Data.SqlClient/SqlCommand.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #1195](https://github.com/dotnet/dotnet-api-docs/issues/1195) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @Siox0911 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/dotnet/dotnet-api-docs/issues/1195. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
