### ISSUE TITLE
Poor translation of so many articles

### ISSUE THREAD

**Issue by DaveTW-Berlin** [dotnet/dotnet-api-docs.de-de#8]
Beside the fact, that docs.microsoft.com is sooo slow, the automatic german translation of the .NET API is almost not understandeable. Please compare it to your existing, very good german documentation of the same articles with selected ".NET Framework 3.5". These seem to be translated by real persons with fundamental knowledge of german grammar and vokabulary.
As a workaround please use the 3.5-branch as a base and extend it with eventually added informations. 

With best regards,
David

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e45eceaa-9d7f-67b5-1d92-58776c2e137d
* Version Independent ID: ff90e4c3-d9ad-5f91-c3b8-851b6b577649
* Content: [File.Exists(String) Method (System.IO)](https://docs.microsoft.com/de-de/dotnet/api/system.io.file.exists?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(System.IO.File.Exists)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netframework-3.5)
* Content Source: [xml/System.IO/File.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.IO/File.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hello, @DaveTW-Berlin 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Kind regards,
Microsoft DOCS International Team
